# Generated by Django 5.2.4 on 2025-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CLASICOS', 'Clásicos'), ('TERROR', 'Terror'), ('FANTASIA', 'Fantasía'), ('HISTORIA', 'Historia'), ('POESIA', 'Poesía'), ('MUSICA', 'Música')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SesionComputadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_uso_minutos', models.IntegerField()),
                ('sitios_web_visitados', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
